{{- if .Values.containers }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  annotations:
    checksum/configmaps: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "instant-chart.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "instant-chart.labels" . | nindent 8 }}
    spec:
      containers:
      {{- range $index, $container := .Values.containers }}
      - name: {{ $container.name | default (printf "container-%d" $index) }}
        {{- omit $container  "name" | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
      {{- range $index, $container := . }}
      - name: {{ $container.name | default (printf "init-%d" $index) }}
        {{- omit $container  "name" | toYaml | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.volumes }}
      volumes:
      {{- include "instant-chart.volumes" . | nindent 6 -}}
      {{- end -}}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "instant-chart.serviceAccountName" . }}
      {{- end }}
      {{- if or .Values.registryLogin .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- if .Values.registryLogin }}
      - name: {{ include "instant-chart.pullSecretName" . }}
      {{- end }}
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeName }}
      nodeName: {{ . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.overhead }}
      overhead:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.readinessGates }}
      readinessGates:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
