{{- if .Values.registryLogin }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instant-chart.pullSecretName" . }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "instant-chart.dockerconfigjson" .Values.registryLogin }}
{{- end }}
