{{- if .Values.secrets -}}
{{- range $name, $data := .Values.secrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}
  labels:
    {{- include "instant-chart.labels" $ | nindent 4 }}
  {{- with $.Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := $data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
