{{- if and .Values.service.enabled .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "instant-chart.matchLabels" . | nindent 4 }}
  {{- with .Values.service }}
  ports:
  {{- range $index, $port := .ports }}
  - name: {{ .name | default (printf "port-%d" $index) }}
    port: {{ $port.port | default 80 }}
    targetPort: {{ $port.targetPort | default $port.port | default 80 }}
    {{- $extra := omit .  "name" "port" "targetPort" "protocol" -}}
    {{- if $extra }}
    {{- toYaml $extra | nindent 4 }}
    {{- end }}
    protocol: {{ $port.protocol | default "TCP" }}
  {{- end }}
  {{- toYaml (omit .  "enabled" "selector" "annotations" "labels" "ports") | nindent 2 }}
  {{- end }}
{{- end }}
