{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "instant-chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "instant-chart.matchLabels" . | nindent 4 }}
  {{- with .Values.service }}
  {{- $service := omit .  "enabled" "selector" "annotations" "labels" }}
  {{- toYaml $service | nindent 2 }}
  {{- end }}
{{- end }}
