apiVersion: v2
name: instant-chart
description: A Helm chart enables rapid deployment
type: application
version: 0.4.0
dependencies:
  - name: common
    version: 2.20.5
    repository: https://charts.bitnami.com/bitnami
